### ISSUE TITLE
Screenshot im Chrome Store fehlt

### ISSUE THREAD

**Issue by aggsol** [Stitch7/mservice-webextension#1]
Nicht, daß es durch ein Screenshot vom 3-Frame-Forum besser würde ;-P

**Comment by Stitch7** [comment]
Extra für dich ein wunderschöner [Screenshot](https://chrome.google.com/webstore/detail/mservice/cilgdabbhoaegpnapbkaioeafgikjgdi), wo man doch von der Extension so viel sieht ;)

Hast du es mal ausprobiert? Delayed halt wie es aktuell gemacht ist etwas bis die Links alle eingefärbt sind, aber ich find's nützlich.
Wollte mit dem Announcement im Forum warten bis auch die Firefox Version bereit ist, aber das Review bei Mozilla dauert...
Gestern haben sie mich angeschrieben und was kritisiert, s. [c2effb0](https://github.com/Stitch7/mservice-webextension/commit/c2effb0d9484d162803dadbcfe1ede58b915ea7b). 
Hab jetzt eine neue Version hoch geschoben und hoffe das ist jetzt bald online.
